#!/bin/sh

set -e

case "$1" in
   configure)
	systemctl mask systemd-resolved.service
   ;;

   abort-upgrade|abort-remove|abort-deconfigure)
   ;;

   *)
       exit 1
   ;;
esac

#DEBHELPER#

exit 0

